TASK 2: CUISINE COMBINATION
Dataset: Zomato Restaurants Dataset(Kaggle)
Goal: Identifying the most common combinations of cuisines in the dataset and to determine if certain cuisines combinations tend to have higher ratings.

Step 1: Load the dataset

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Desktop\zomato.csv", encoding='latin-1')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

Step 2: Most commom cuisine combination

In [4]:
Cuisine_combo_counts = df['Cuisines'].value_counts().head(15)
Cuisine_combo_counts

Cuisines
North Indian                      936
North Indian, Chinese             511
Chinese                           354
Fast Food                         354
North Indian, Mughlai             334
Cafe                              299
Bakery                            218
North Indian, Mughlai, Chinese    197
Bakery, Desserts                  170
Street Food                       149
Pizza, Fast Food                  131
Chinese, Fast Food                118
Mithai, Street Food               116
South Indian                      112
Bakery, Fast Food                 108
Name: count, dtype: int64

In [5]:
print(df.columns.tolist())

['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address', 'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating', 'Rating color', 'Rating text', 'Votes']

Step 3: Average rating per cuisine combination

In [6]:
Cuisine_ratings = df.groupby('Cuisines')['Aggregate rating'].mean().sort_values(ascending=False)
Cuisine_ratings.head(15)

Cuisines
Italian, Deli                      4.9
Hawaiian, Seafood                  4.9
American, Sandwich, Tea            4.9
Continental, Indian                4.9
European, Asian, Indian            4.9
European, Contemporary             4.9
European, German                   4.9
BBQ, Breakfast, Southern           4.9
American, Coffee and Tea           4.9
Sunda, Indonesian                  4.9
American, Burger, Grill            4.9
Mughlai, Lucknowi                  4.9
Mexican, American, Healthy Food    4.9
American, Caribbean, Seafood       4.9
Burger, Bar Food, Steak            4.9
Name: Aggregate rating, dtype: float64

Problem: First attempt without filtering reveals a common data pitfall. The top results all show a perfect 4.9 rating which is misleading.
To fix: filter combinations with a reasonable sample size(at least 20 resturants).

In [10]:
combo_stats = df.groupby('Cuisines').agg(
    avg_rating=('Aggregate rating', 'mean'),
    restaurant_count=('Aggregate rating', 'count')
)

# only keep combos with at least 20 restaurants
reliable_combos = combo_stats[combo_stats['restaurant_count'] >=20].sort_values('avg_rating', ascending=False)
reliable_combos.head(15)

                                    avg_rating  restaurant_count
Cuisines
American                              3.667742                31
Italian                               3.657407                54
Italian, Pizza                        3.637500                24
Mexican                               3.636111                36
Continental                           3.566667                21
Fast Food, Burger                     3.403571                56
Cafe, Tea                             3.375000                20
Bakery, Desserts, Fast Food           3.366667                63
American, Fast Food                   3.350000                20
Chinese, Thai                         3.309804                51
Desserts, Ice Cream                   3.296154                26
North Indian, Continental             3.264286                28
Burger, Fast Food                     3.169767                43
Burger, Desserts, Fast Food           3.136364                22
North Indian, Chinese, Continental    3.036923                65

CONCLUSION
The most popular cuisine combinations are not necessarily the highest-rated ones. Single-cuisine, internationally-themed restaurants tends to outperform broad multi-cuisine combinations in customer satisfaction.